### ISSUE TITLE
[PE-D] Inconsistent naming convention

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T09-2/tp#206] opened 2022-04-01 15:22 UTC
The naming of plan is case insensitive when user add new plan in the application. Eg. Users cannot add both plan a and Plan A.
Therefore, it is assumed that the naming is also case insensitive in local file. Eg. Both plan a and Plan A should work.
However, the following changes that was made in the local file has introduced an error in the application. 

![Screenshot 2022-04-01 at 17.43.18.png](https://raw.githubusercontent.com/yanjie1017/ped/main/files/af4e6e37-717e-442d-82c0-2a0a1c0bcb95.png)

![Screenshot 2022-04-01 at 17.44.24.png](https://raw.githubusercontent.com/yanjie1017/ped/main/files/29137532-6724-47d5-b68a-13743aa7881d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yanjie1017/ped#4

**Comment by alanlowzies** [comment] 2022-04-03 15:20
Will update the UG to warn users not to modify the resource files. Otherwise, app will crash.

**Comment by Musfirahe0556596** [comment] 2022-04-03 15:53
Additionally, add in DG for design consideration.
Fixed in #218. By design, we delete inconsistent plan names between schedules and plans.

**Comment by Musfirahe0556596** [comment] 2022-04-05 19:20
Fixed in PR #248 . All the local upper cases will be converted to lower cases upon loading of data.

**Closed** 2022-04-06 17:25 UTC
Labels: documentation
